# Sample Launcher of embedded Tomcat

Just run the grade task startTomcat.

[source]
----
./gradlew startTomcat
----

Open http://localhost:8080 and http://localhost:8080/hello in your browser.
It will either show index.html or the HelloServlet output.
Changes to index.html will be automatically active after a page reload.
Changes to the servlet's source code need a rebuild and restart.
Jrebel can help with that issue.

The root project contains the index.html and the HelloServlet class.
It has a compile time dependency on javax.servlet-api for the servlet.

The subproject tomcat-embedded-launcher contains the launcher class TomcatLauncher.
It has the necessary dependencies on tomcat-embedded.
The root project defines a gradle task startTomcat to launch the app.

The core idea is copied from https://devcenter.heroku.com/articles/create-a-java-web-application-using-embedded-tomcat and https://github.com/heroku/devcenter-embedded-tomcat .

## Using in unit tests

The class link:src/test/java/xyz/its_me/TomcatTest.java[TomcatTest] shows how this can be used in unit tests.
The test methods can interact both with the main code by java calls and with the webapplication by HTTP.

## Continuous Integration thanks to Snap CI

Build image:https://snap-ci.com/torstenwerner/tomcat-embedded/branch/master/build_image[status]
at link:https://snap-ci.com/torstenwerner/tomcat-embedded/branch/master[Snap CI]
